# Generated by Django 5.1 on 2026-06-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='クーポンコード')),
                ('discount_percent', models.IntegerField(verbose_name='割引率(%)')),
                ('used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='発行日時')),
            ],
            options={
                'db_table': 'shopping_coupon',
            },
        ),
    ]
